apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workwave-app
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: https://github.com/Monzy-B/DevOps-Class.git
    targetRevision: patch-1
    path: ./todo-app            
    helm:
      releaseName: workwave-app
      valueFiles:
        - values.yaml   
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
