apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    app: weather
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather-app
          image: tomiwadevops/weather-app:ci-cd  # jephnewman/workwave:workwave-image
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"        
              memory: "128Mi"    
            limits:
              cpu: "500m"        
              memory: "256Mi"    
